### ISSUE TITLE
Make code conform to PEP 8

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-python#1]
We'd like the code to comply with http://www.python.org/dev/peps/pep-0008/ and have a script we can run to detect (and hopefully fix) code that is not compliant.

**Comment by rliebz** [comment]
I recommend using [flake8](https://flake8.readthedocs.org/en/2.3.0/). It can be easily run with `$ flake8 .`, and is fairly easily configurable. For an example of a configuration file in use, see https://github.com/CenterForOpenScience/osf.io/blob/develop/setup.cfg.
