### ISSUE TITLE
Support editing the metadata of a dataset using JSON

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-python#15]
As I mentioned at https://github.com/IQSS/dataverse/issues/2062#issuecomment-94869103 we could add a Subject to a dataset that doesn't have one by pulling down the JSON of a dataset, making some modifications, and re-uploading the JSON. Here's an example script that does this (as of this writing it changes the title of the dataset):

https://github.com/IQSS/dataverse/blob/master/scripts/search/tests/edit-dataset-finch1

We wouldn't be limited to only adding a Subject, of course. You can express any metadata field in JSON: http://guides.dataverse.org/en/latest/user/dataset-management.html#supported-metadata

**Comment by garthg** [comment]
Hi,

I'm a developer making use of Dataverse infrastructure for another Harvard project (my project at https://github.com/garthg/petitions-dataverse making use of the Dataverse at https://dataverse.harvard.edu/dataverse/antislaverypetitionsma). The feature described in this tracker, i.e. making JSON modifications to Dataverse entries using the Python client, would be useful for our work, so I wanted to say that I am in favor of this feature request!

Thanks to all the developers for their work.

Garth

**Comment by rliebz** [comment]
This feature has been added in the latest (poorly-named) development branch (See #14). Since I'm breaking a fair amount of backward compatibility, I wanted to bundle the changes together before merging.
