### ISSUE TITLE
Unable to clone this repo

### ISSUE THREAD

**Issue by sloria** [IQSS/dataverse-client-python#31]
As of today, I am unable to clone this repo from either the HTTPS or SSH urls.

Here is the output:

```
$ git clone https://github.com/IQSS/dataverse-client-python.git                                                                                                                              
Cloning into 'dataverse-client-python'...
fatal: unable to access 'https://github.com/IQSS/dataverse-client-python.git/': transfer closed with outstanding read data remaining
$ git clone git@github.com:IQSS/dataverse-client-python.git                                                                                                                                  
Cloning into 'dataverse-client-python'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I also cannot clone any forks of this repo. This is causing our CI to fail (example build: https://travis-ci.org/CenterForOpenScience/osf.io/jobs/125595166).

**Comment by pdurbin** [comment]
@sloria that's funny, I just ran a build on Travis the `git clone` worked fine: https://travis-ci.org/IQSS/dataverse-client-python/jobs/84656584

However, some tests are failing such as "test_add_files FAILED":

![screen shot 2016-04-25 at 12 41 05 pm](https://cloud.githubusercontent.com/assets/21006/14791267/1d0a6a16-0ae3-11e6-8185-e10ef483ce31.png)

I see what you mean about being unable to clone forks from Travis but it seems to work fine for me from a random Linux box with no special permissions to GitHub.:

```
[root@dvnweb-vm2 ~]# mkdir /tmp/foobar
[root@dvnweb-vm2 ~]# cd /tmp/foobar
[root@dvnweb-vm2 foobar]# git clone https://github.com/CenterForOpenScience/dataverse-client-python.git
Initialized empty Git repository in /tmp/foobar/dataverse-client-python/.git/
remote: Counting objects: 705, done.
remote: Total 705 (delta 0), reused 0 (delta 0), pack-reused 705
Receiving objects: 100% (705/705), 157.74 KiB, done.
Resolving deltas: 100% (412/412), done.
[root@dvnweb-vm2 foobar]# 
```

Please let us know how we can help.

**Comment by sloria** [comment]
Looks like GitHub has resolved the issue. Thanks for looking into this.

**Comment by pdurbin** [comment]
Oh sure. Glad you're all set.
