### ISSUE TITLE
Key protected API

### ISSUE THREAD

**Issue by jri-sp** [IQSS/dataverse-client-python#35]
Hi,

I'm trying to use your client for creating dataverses. I'm making a script which work with your lib destinated to final users. 
So they can't go to the production server to execute the script on localhost.
I'm trying to open the API like said here: http://guides.dataverse.org/en/latest/installation/config.html#blockedapipolicy

I've set a key and the "unblock-key" policy. But I don't find how to specify the key for the python library.

Could you help me ? :/

Regards

**Comment by jri-sp** [comment]
More explanations given by @pdurbin on IRC.
I think I was in a wrong way, my problem seems to be elsewhere.

IRC Log: http://irclog.iq.harvard.edu/dataverse/2016-08-16#i_39461

**Comment by pdurbin** [comment]
The problem is probably that the Dataverse docs aren't clear enough! @jri-sp please feel free to make a pull request! http://guides.dataverse.org/en/4.4/developers/documentation.html 😄
