### ISSUE TITLE
merge rliebz/dvn-client-python into IQSS/dvn-client-python

### ISSUE THREAD

**Issue by codersquid** [IQSS/dataverse-client-python#7]
https://github.com/IQSS/dvn-client-python/pull/5

I reverted the merge I made from @rliebz and since there doesn't seem to be a way to reopen a pull request, I'm creating this issue to track it.

**Comment by rliebz** [comment]
Resolved by 8f10d96f203bbd95a83b3c55577a7bcf984c743c
